In [1]:
import keras
import tensorflow as tf
print(keras.__version__)
print(tf.__version__)

2021-12-21 15:33:07.636536: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-21 15:33:07.636592: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


2.5.0
2.5.2


In [2]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

NGRAMS = 2
SAMPLE = 1000000
EPOCHS = 15

# Florida voter
df = pd.read_csv('/opt/data/fl_voterreg/fl_reg_name_race.csv.gz')
df.dropna(subset=['name_first', 'name_last'], inplace=True)
sdf = df[df.race.isin(['multi_racial', 'native_indian', 'other', 'unknown']) == False].sample(SAMPLE, random_state=21)
del df

# Additional features
sdf['name_first'] = sdf.name_first.str.title()
sdf['name_last'] = sdf.name_last.str.title()

sdf

name_last  name_first      race
5577783          Lidros       Johan  nh_white
11025099         Dionne        John  nh_white
9175381   Serrano Ortiz       Hilda  hispanic
511481          Hampton       Tracy  nh_white
336833         Mitchell     Michael  nh_white
...                 ...         ...       ...
7765170          Osipov  Konstantin  nh_white
8437763        Ammerman      Daniel  nh_white
816193         Goldberg    Randolph  nh_white
13135601        Carrick      Donald  nh_white
1545274         Mc Minn     Beverly  nh_white

[1000000 rows x 3 columns]

In [3]:
rdf = sdf.groupby('race').agg({'name_first': 'count'})
rdf.to_csv('./fl_voter_reg/lstm/fl_name_race.csv', columns=[])
rdf

name_first
race                
asian          19382
hispanic      167274
nh_black      141448
nh_white      671896

In [4]:
sdf.groupby('race').agg({'name_last': 'nunique'})

name_last
race               
asian          9362
hispanic      41246
nh_black      22837
nh_white     145560

## Preprocessing the input data

In [5]:
# concat last name and first name
sdf['name_last_name_first'] = sdf['name_last'] + ' ' + sdf['name_first']

# build n-gram list
vect = CountVectorizer(analyzer='char', max_df=0.3, min_df=3, ngram_range=(NGRAMS, NGRAMS), lowercase=False) 
a = vect.fit_transform(sdf.name_last_name_first)
vocab = vect.vocabulary_

# sort n-gram by freq (highest -> lowest)
words = []
for b in vocab:
    c = vocab[b]
    #print(b, c, a[:, c].sum())
    words.append((a[:, c].sum(), b))
    #break
words = sorted(words, reverse=True)
words_list = ['UNK']
words_list.extend([w[1] for w in words])
num_words = len(words_list)
print("num_words = %d" % num_words)


def find_ngrams(text, n):
    a = zip(*[text[i:] for i in range(n)])
    wi = []
    for i in a:
        w = ''.join(i)
        try:
            idx = words_list.index(w)
        except:
            idx = 0
        wi.append(idx)
    return wi

# build X from index of n-gram sequence
X = np.array(sdf.name_last_name_first.apply(lambda c: find_ngrams(c, NGRAMS)))

# check max/avg feature
X_len = []
for x in X:
    X_len.append(len(x))

max_feature_len = max(X_len)
avg_feature_len = int(np.mean(X_len))

print("Max feature len = %d, Avg. feature len = %d" % (max_feature_len, avg_feature_len))
y = np.array(sdf.race.astype('category').cat.codes)

# Split train and test dataset
X_train,  X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

num_words = 1260
Max feature len = 41, Avg. feature len = 12


## Train a LSTM model

ref: http://machinelearningmastery.com/sequence-classification-lstm-recurrent-neural-networks-python-keras/

In [6]:
'''The dataset is actually too small for LSTM to be of any advantage
compared to simpler, much faster methods such as TF-IDF + LogReg.
Notes:

- RNNs are tricky. Choice of batch size is important,
choice of loss and optimizer is critical, etc.
Some configurations won't converge.

- LSTM loss decrease patterns during training can be quite different
from what you see with CNNs/MLPs/etc.
'''
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding, Dropout, Activation
from keras.layers import LSTM
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.models import load_model

max_features = num_words # 20000
feature_len = 25 # avg_feature_len # cut texts after this number of words (among top max_features most common words)
batch_size = 32

print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')

print('Pad sequences (samples x time)')
X_train = sequence.pad_sequences(X_train, maxlen=feature_len)
X_test = sequence.pad_sequences(X_test, maxlen=feature_len)
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

num_classes = np.max(y_train) + 1
print(num_classes, 'classes')

print('Convert class vector to binary class matrix '
      '(for use with categorical_crossentropy)')
y_train = tf.keras.utils.to_categorical(y_train, num_classes)
y_test = tf.keras.utils.to_categorical(y_test, num_classes)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

800000 train sequences
200000 test sequences
Pad sequences (samples x time)
X_train shape: (800000, 25)
X_test shape: (200000, 25)
4 classes
Convert class vector to binary class matrix (for use with categorical_crossentropy)
y_train shape: (800000, 4)
y_test shape: (200000, 4)


In [7]:
print('Build model...')

model = Sequential()
model.add(Embedding(num_words, 32, input_length=feature_len))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(num_classes, activation='softmax'))

# try using different optimizers and different optimizer configs
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print(model.summary())

Build model...
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 25, 32)            40320     
_________________________________________________________________
lstm (LSTM)                  (None, 128)               82432     
_________________________________________________________________
dense (Dense)                (None, 4)                 516       
Total params: 123,268
Trainable params: 123,268
Non-trainable params: 0
_________________________________________________________________
None


2021-12-21 15:36:04.374035: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-12-21 15:36:04.374094: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-12-21 15:36:04.374122: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (jupyter-server-2): /proc/driver/nvidia/version does not exist
2021-12-21 15:36:04.374353: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
print('Train...')
model.fit(X_train, y_train, batch_size=batch_size, epochs=EPOCHS,
          validation_split=0.1, verbose=1)
score, acc = model.evaluate(X_test, y_test,
                            batch_size=batch_size, verbose=1)
print('Test score:', score)
print('Test accuracy:', acc)

Train...


2021-12-21 15:36:04.839015: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-12-21 15:36:04.839629: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2250000000 Hz


Epoch 1/15
22500/22500 [==============================] - 701s 30ms/step - loss: 0.6106 - accuracy: 0.7788 - val_loss: 0.5192 - val_accuracy: 0.8136
Epoch 2/15
22500/22500 [==============================] - 664s 30ms/step - loss: 0.5200 - accuracy: 0.8124 - val_loss: 0.4948 - val_accuracy: 0.8243
Epoch 3/15
22500/22500 [==============================] - 776s 34ms/step - loss: 0.4955 - accuracy: 0.8222 - val_loss: 0.4810 - val_accuracy: 0.8296
Epoch 4/15
22500/22500 [==============================] - 782s 35ms/step - loss: 0.4816 - accuracy: 0.8278 - val_loss: 0.4723 - val_accuracy: 0.8342
Epoch 5/15
22500/22500 [==============================] - 764s 34ms/step - loss: 0.4751 - accuracy: 0.8308 - val_loss: 0.4699 - val_accuracy: 0.8338
Epoch 6/15
22500/22500 [==============================] - 995s 44ms/step - loss: 0.4695 - accuracy: 0.8329 - val_loss: 0.4654 - val_accuracy: 0.8369
Epoch 7/15
22500/22500 [==============================] - 1149s 51ms/step - loss: 0.4655 - accuracy: 0.834

In [9]:
print('Test score:', score)
print('Test accuracy:', acc)

Test score: 0.45394647121429443
Test accuracy: 0.8408349752426147


## Confusion Matrix

In [10]:
p = model.predict(X_test, verbose=2) # to predict probability
y_pred = np.argmax(p, axis=-1)
target_names = list(sdf.race.astype('category').cat.categories)
print(classification_report(np.argmax(y_test, axis=1), y_pred, target_names=target_names))
print(confusion_matrix(np.argmax(y_test, axis=1), y_pred))

6250/6250 - 32s
              precision    recall  f1-score   support

       asian       0.81      0.42      0.55      3876
    hispanic       0.82      0.86      0.84     33455
    nh_black       0.76      0.43      0.55     28290
    nh_white       0.86      0.93      0.89    134379

    accuracy                           0.84    200000
   macro avg       0.81      0.66      0.71    200000
weighted avg       0.83      0.84      0.83    200000

[[  1612    478    236   1550]
 [    66  28643    457   4289]
 [    76    666  12290  15258]
 [   231   5291   3235 125622]]


## Save model

In [11]:
model.save('./fl_voter_reg/lstm/fl_all_name_lstm.h5')

In [12]:
words_df = pd.DataFrame(words_list, columns=['vocab'])
words_df.to_csv('./fl_voter_reg/lstm/fl_all_name_vocab.csv', index=False, encoding='utf-8')
