In [1]:
from __future__ import print_function

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

NGRAMS = 2
EPOCHS = 5
#YEAR = '2000'
YEAR = '2010'

df = pd.read_csv('../../data/census/census_%s.csv' % YEAR)
df.dropna(subset=['name'], inplace=True)
df.replace('(S)', 0, inplace=True)
df

name    rank     count  prop100k  cum_prop100k pctwhite  \
0                 SMITH       1   2442977    828.19        828.19     70.9   
1               JOHNSON       2   1932812    655.24       1483.42    58.97   
2              WILLIAMS       3   1625252    550.97       2034.39    45.75   
3                 BROWN       4   1437026    487.16       2521.56    57.95   
4                 JONES       5   1425470    483.24       3004.80    55.19   
...                 ...     ...       ...       ...           ...      ...   
162249        DIETZMANN  160975       100      0.03      90062.93       96   
162250            DOKAS  160975       100      0.03      90062.96       94   
162251           DONLEA  160975       100      0.03      90062.99       94   
162252          DORIOTT  160975       100      0.03      90063.03       89   
162253  ALL OTHER NAMES       0  29312001   9936.97       9936.97    66.65   

       pctblack pctapi pctaian pct2prace pcthispanic  
0         23.11    0.5    0.89      2.19         2.4  
1         34.63   0.54    0.94      2.56        2.36  
2         47.68   0.46    0.82      2.81        2.49  
3          35.6   0.51    0.87      2.55        2.52  
4         38.48   0.44       1      2.61        2.29  
...         ...    ...     ...       ...         ...  
162249        0      0       0         0           0  
162250        0      0       0         0           0  
162251        0      0       0         0           6  
162252        0      0       0         5           0  
162253     8.53   7.97    0.86      2.32       13.67  

[162253 rows x 11 columns]

## Resampling with weight

In [2]:
sdf = df.sample(1000000, weights=df['count'], replace=True)

## Assign race by pertcentage

In [3]:
from numpy.random import choice

races = ['white', 'black', 'api', 'hispanic']

def to_race(c):
    w = np.array(c).astype(float)
    if w.sum() == 0:
        return 'white'
    probs = w/w.sum()
    return choice(races, p=probs)

sdf['race'] = sdf[['pctwhite', 'pctblack', 'pctapi', 'pcthispanic']].apply(lambda c: to_race(c), axis=1)
sdf

name    rank     count  prop100k  cum_prop100k pctwhite  \
4                 JONES       5   1425470    483.24       3004.80    55.19   
144925         SCHURGER  144141       115      0.04      89435.56    98.26   
194               PAYNE     195    142601     48.34      23037.13    71.55   
149                CHEN     150    169580     57.49      20664.71      1.4   
39               FLORES      40    433969    147.12      11243.84     4.87   
...                 ...     ...       ...       ...           ...      ...   
10840           PEIFFER   10837      2938      1.00      69235.34    95.98   
2158             BARROW    2159     16801      5.70      50250.23    66.63   
1987              MCRAE    1987     18156      6.16      49239.38     52.7   
22             THOMPSON      23    664644    225.32       8302.08    69.78   
162253  ALL OTHER NAMES       0  29312001   9936.97       9936.97    66.65   

       pctblack pctapi pctaian pct2prace pcthispanic      race  
4         38.48   0.44       1      2.61        2.29     white  
144925        0      0       0         0           0     white  
194       22.63   0.45    0.58      2.37        2.42     white  
149         0.3  96.12    0.02      1.64        0.52       api  
39         0.42   2.08    0.34      0.36       91.94  hispanic  
...         ...    ...     ...       ...         ...       ...  
10840      0.44   0.54    0.34      1.09         1.6     white  
2158      26.67   0.51    0.55      2.14        3.49  hispanic  
1987      41.41   0.41    0.44      2.46        2.58     white  
22        23.57   0.57    1.22      2.37        2.49     white  
162253     8.53   7.97    0.86      2.32       13.67       api  

[1000000 rows x 12 columns]

## Check the correctness of race assignment

In [4]:
df[df.name == 'SMITH']

name  rank    count  prop100k  cum_prop100k pctwhite pctblack pctapi  \
0  SMITH     1  2442977    828.19        828.19     70.9    23.11    0.5   

  pctaian pct2prace pcthispanic  
0    0.89      2.19         2.4

In [5]:
xdf = sdf[sdf.name=='SMITH'].groupby(['race']).agg({'name': 'count'})
xdf * 100 / xdf.sum()

name
race               
api        0.534564
black     24.322683
hispanic   2.636375
white     72.506378

In [6]:
# Additional features
sdf['name_last'] = sdf.name.str.title()
sdf.groupby('race').agg({'name_last': 'count'})

name_last
race               
api           50010
black        124213
hispanic     165099
white        660678

In [7]:
len(sdf)

1000000

## Preprocessing the input data

In [8]:
# only last name in Census data
sdf['name_last_name_first'] = sdf['name_last']

# build n-gram list
vect = CountVectorizer(analyzer='char', max_df=0.3, min_df=3, ngram_range=(NGRAMS, NGRAMS), lowercase=False) 
#vect = CountVectorizer(analyzer='char', ngram_range=(2, 2), lowercase=False) 
a = vect.fit_transform(sdf.name_last_name_first)
vocab = vect.vocabulary_
len(vocab)

973

In [9]:
import operator
sorted_vocab = sorted(vocab.items(), key=operator.itemgetter(1))
cols = list(map(operator.itemgetter(0), sorted_vocab))

In [10]:
count_df = pd.DataFrame(a.todense(), columns=cols)
count_df

N   O  Aa  Ab  Ac  Ad  Ae  Af  Ag  Ah  ...  zp  zq  zr  zs  zt  zu  \
0        0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
1        0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
2        0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
3        0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
4        0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..   
999995   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
999996   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
999997   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
999998   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   
999999   1   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   

        zv  zw  zy  zz  
0        0   0   0   0  
1        0   0   0   0  
2        0   0   0   0  
3        0   0   0   0  
4        0   0   0   0  
...     ..  ..  ..  ..  
999995   0   0   0   0  
999996   0   0   0   0  
999997   0   0   0   0  
999998   0   0   0   0  
999999   0   0   0   0  

[1000000 rows x 973 columns]

In [11]:
count_df.sum().sort_values(ascending=False).describe()

count       973.000000
mean       6347.018499
std       18212.901816
min           3.000000
25%          80.000000
50%         833.000000
75%        5050.000000
max      253964.000000
dtype: float64

In [12]:
pd.set_option('display.max_rows', 20)
count_df.sum().sort_values(ascending=False)

er    253964
ll    174869
es    144194
am    131946
he    124439
       ...  
Uj         3
Uf         3
qe         3
bj         3
jz         3
Length: 973, dtype: int64

In [13]:
# sort n-gram by freq (highest -> lowest)
words = []
for b in vocab:
    c = vocab[b]
    #print(b, c, a[:, c].sum())
    words.append((a[:, c].sum(), b))
    #break
words = sorted(words, reverse=True)
words_list = [w[1] for w in words]
num_words = len(words_list)
print("num_words = %d" % num_words)

num_words = 973


In [14]:
def find_ngrams(text, n):
    a = zip(*[text[i:] for i in range(n)])
    wi = []
    for i in a:
        w = ''.join(i)
        try:
            idx = words_list.index(w)
        except:
            idx = 0
        wi.append(idx)
    return wi

# build X from index of n-gram sequence
X = np.array(sdf.name_last_name_first.apply(lambda c: find_ngrams(c, NGRAMS)))

# check max/avg feature
X_len = []
for x in X:
    X_len.append(len(x))

max_feature_len = max(X_len)
avg_feature_len = int(np.mean(X_len))

print("Max feature len = %d, Avg. feature len = %d" % (max_feature_len, avg_feature_len))
y = np.array(sdf.race.astype('category').cat.codes)

# Split train and test dataset
X_train,  X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

Max feature len = 14, Avg. feature len = 6


## Train a LSTM model

ref: http://machinelearningmastery.com/sequence-classification-lstm-recurrent-neural-networks-python-keras/

In [15]:
'''The dataset is actually too small for LSTM to be of any advantage
compared to simpler, much faster methods such as TF-IDF + LogReg.
Notes:

- RNNs are tricky. Choice of batch size is important,
choice of loss and optimizer is critical, etc.
Some configurations won't converge.

- LSTM loss decrease patterns during training can be quite different
from what you see with CNNs/MLPs/etc.
'''
import keras
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding, Dropout, Activation
from keras.layers import LSTM
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.models import load_model

max_features = num_words # 20000
feature_len = 20 # avg_feature_len # cut texts after this number of words (among top max_features most common words)
batch_size = 32

print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')

print('Pad sequences (samples x time)')
X_train = sequence.pad_sequences(X_train, maxlen=feature_len)
X_test = sequence.pad_sequences(X_test, maxlen=feature_len)
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

num_classes = np.max(y_train) + 1
print(num_classes, 'classes')

print('Convert class vector to binary class matrix '
      '(for use with categorical_crossentropy)')
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

800000 train sequences
200000 test sequences
Pad sequences (samples x time)
X_train shape: (800000, 20)
X_test shape: (200000, 20)
4 classes
Convert class vector to binary class matrix (for use with categorical_crossentropy)
y_train shape: (800000, 4)
y_test shape: (200000, 4)


In [16]:
print('Build model...')

model = Sequential()
model.add(Embedding(num_words, 32, input_length=feature_len))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(num_classes, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print(model.summary())

Build model...
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 32)            31136     
_________________________________________________________________
lstm (LSTM)                  (None, 128)               82432     
_________________________________________________________________
dense (Dense)                (None, 4)                 516       
Total params: 114,084
Trainable params: 114,084
Non-trainable params: 0
_________________________________________________________________
None


In [17]:
print('Train...')
model.fit(X_train, y_train, batch_size=batch_size, epochs=EPOCHS,
          validation_split=0.1, verbose=2)
score, acc = model.evaluate(X_test, y_test,
                            batch_size=batch_size, verbose=2)
print('Test score:', score)
print('Test accuracy:', acc)

Train...
Epoch 1/5
22500/22500 - 676s - loss: 0.6520 - accuracy: 0.7770 - val_loss: 0.6263 - val_accuracy: 0.7855
Epoch 2/5
22500/22500 - 1052s - loss: 0.6138 - accuracy: 0.7895 - val_loss: 0.6070 - val_accuracy: 0.7925
Epoch 3/5
22500/22500 - 1141s - loss: 0.6004 - accuracy: 0.7938 - val_loss: 0.5967 - val_accuracy: 0.7953
Epoch 4/5
22500/22500 - 967s - loss: 0.5927 - accuracy: 0.7959 - val_loss: 0.5893 - val_accuracy: 0.7968
Epoch 5/5
22500/22500 - 622s - loss: 0.5878 - accuracy: 0.7973 - val_loss: 0.5864 - val_accuracy: 0.7972
6250/6250 - 18s - loss: 0.5835 - accuracy: 0.7986
Test score: 0.5835372805595398
Test accuracy: 0.7986400127410889


## Confusion Matrix

In [18]:
y_pred = model.predict_classes(X_test, verbose=2)
p = model.predict_proba(X_test, verbose=2) # to predict probability
target_names = list(sdf.race.astype('category').cat.categories)
print(classification_report(np.argmax(y_test, axis=1), y_pred, target_names=target_names))
print(confusion_matrix(np.argmax(y_test, axis=1), y_pred))

/Users/madhusanjeevi/Desktop/GauravFreelanceing/env/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


6250/6250 - 18s


/Users/madhusanjeevi/Desktop/GauravFreelanceing/env/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


6250/6250 - 19s
              precision    recall  f1-score   support

         api       0.84      0.56      0.67     10002
       black       0.53      0.07      0.13     24843
    hispanic       0.87      0.76      0.81     33020
       white       0.79      0.96      0.87    132135

    accuracy                           0.80    200000
   macro avg       0.76      0.59      0.62    200000
weighted avg       0.77      0.80      0.76    200000

[[  5633     30    797   3542]
 [   246   1764    257  22576]
 [   166    110  25153   7591]
 [   687   1442   2828 127178]]


## Save model

In [19]:
model.save('./models/census/lstm/census%s_ln_lstm.h5' % YEAR)

In [20]:
words_df = pd.DataFrame(words_list, columns=['vocab'])
words_df.to_csv('./models/census/lstm/census%s_ln_vocab.csv' % YEAR, index=False, encoding='utf-8')

In [21]:
y_pred = model.predict_classes(X_train, verbose=2)
target_names = list(sdf.race.astype('category').cat.categories)
print(classification_report(np.argmax(y_train, axis=1), y_pred, target_names=target_names))
print(confusion_matrix(np.argmax(y_train, axis=1), y_pred))

/Users/madhusanjeevi/Desktop/GauravFreelanceing/env/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


25000/25000 - 72s
              precision    recall  f1-score   support

         api       0.84      0.57      0.68     40008
       black       0.55      0.07      0.13     99370
    hispanic       0.87      0.77      0.82    132079
       white       0.79      0.96      0.87    528543

    accuracy                           0.80    800000
   macro avg       0.76      0.59      0.62    800000
weighted avg       0.78      0.80      0.76    800000

[[ 22795    132   3162  13919]
 [   944   7196    981  90249]
 [   628    325 101179  29947]
 [  2678   5407  10536 509922]]
