In [1]:
import os
import sys
import pandas as pd
import re
from sklearn.utils import shuffle
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
data_path = "../data/voters_csv/"
columns = ["CountyCode","VoterID","LastName","FirstName","MiddleName","Race","DOB"]
files = os.listdir(data_path)

In [3]:
def tryint(s):
    try:
        return int(s)
    except ValueError:
        return s

def alphanum_key(s):
    return [ tryint(c) for c in re.split('([0-9]+)', s) ]

def sort_nicely(l):
    l.sort(key=alphanum_key)

sort_nicely(files)
files

['ALA_20170207.csv',
 'BAK_20170207.csv',
 'BAY_20170207.csv',
 'BRA_20170207.csv',
 'BRE_20170207.csv',
 'BRO_20170207.csv',
 'CAL_20170207.csv',
 'CHA_20170207.csv',
 'CIT_20170207.csv',
 'CLA_20170207.csv',
 'CLL_20170207.csv',
 'CLM_20170207.csv',
 'DAD_20170207.csv',
 'DES_20170207.csv',
 'DIX_20170207.csv',
 'DUV_20170207.csv',
 'ESC_20170207.csv',
 'FLA_20170207.csv',
 'FRA_20170207.csv',
 'GAD_20170207.csv',
 'GIL_20170207.csv',
 'GLA_20170207.csv',
 'GUL_20170207.csv',
 'HAM_20170207.csv',
 'HAR_20170207.csv',
 'HEN_20170207.csv',
 'HER_20170207.csv',
 'HIG_20170207.csv',
 'HIL_20170207.csv',
 'HOL_20170207.csv',
 'IND_20170207.csv',
 'JAC_20170207.csv',
 'JEF_20170207.csv',
 'LAF_20170207.csv',
 'LAK_20170207.csv',
 'LEE_20170207.csv',
 'LEO_20170207.csv',
 'LEV_20170207.csv',
 'LIB_20170207.csv',
 'MAD_20170207.csv',
 'MAN_20170207.csv',
 'MON_20170207.csv',
 'MRN_20170207.csv',
 'MRT_20170207.csv',
 'NAS_20170207.csv',
 'OKA_20170207.csv',
 'OKE_20170207.csv',
 'ORA_2017020

In [4]:
df = pd.DataFrame(columns=columns)

for file in files:
    temp_df = pd.read_csv(data_path+file)
    df_list = [df, temp_df]
    df = pd.concat(df_list)


In [6]:
df

CountyCode    VoterID     LastName  FirstName MiddleName Race  \
0            ALA  102947246       Walker  Elizabeth          A    5   
1            ALA  122030263       Palmer      Alton    Douglas    5   
2            ALA  101628984     Mc Cleod     Alicia          D    3   
3            ALA  101669113  Scarborough       Dale   Fredrick    5   
4            ALA  101745548       Walker     Daniel        Ray    5   
...          ...        ...          ...        ...        ...  ...   
15804        WAS  100698798      Walters    William     Walter    5   
15805        WAS  104711661       Sawyer    Matthew        Lee    5   
15806        WAS  100726687       Thomas     Janine    O'Riska    5   
15807        WAS  122496331     Campbell      Angel       Rose    7   
15808        WAS  122291178       Bruner        Jeb      Ellis    5   

              DOB  Unnamed: 0  
0      12/28/1961         0.0  
1      03/14/1943         0.0  
2      08/20/1966         0.0  
3      03/07/1951         0.0  
4      06/22/1955         0.0  
...           ...         ...  
15804  07/25/1946         0.0  
15805  07/01/1984         0.0  
15806  03/02/1987         0.0  
15807  08/14/1998         0.0  
15808  04/10/1997         0.0  

[13099661 rows x 8 columns]

In [7]:
df = df.dropna()
df['Race'] = df['Race'].replace([9],8)

<ipython-input-7-455d8b9a0eb4>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Race'] = df['Race'].replace([9],8)


In [8]:
df.Race.value_counts()

5    7648545
3    1396642
4    1239698
8     200862
2     173564
6     143900
7      73845
1      38359
Name: Race, dtype: int64

In [9]:
new_df = df.copy()
new_df

CountyCode    VoterID     LastName  FirstName MiddleName  Race  \
0            ALA  102947246       Walker  Elizabeth          A     5   
1            ALA  122030263       Palmer      Alton    Douglas     5   
2            ALA  101628984     Mc Cleod     Alicia          D     3   
3            ALA  101669113  Scarborough       Dale   Fredrick     5   
4            ALA  101745548       Walker     Daniel        Ray     5   
...          ...        ...          ...        ...        ...   ...   
15804        WAS  100698798      Walters    William     Walter     5   
15805        WAS  104711661       Sawyer    Matthew        Lee     5   
15806        WAS  100726687       Thomas     Janine    O'Riska     5   
15807        WAS  122496331     Campbell      Angel       Rose     7   
15808        WAS  122291178       Bruner        Jeb      Ellis     5   

              DOB  Unnamed: 0  
0      12/28/1961         0.0  
1      03/14/1943         0.0  
2      08/20/1966         0.0  
3      03/07/1951         0.0  
4      06/22/1955         0.0  
...           ...         ...  
15804  07/25/1946         0.0  
15805  07/01/1984         0.0  
15806  03/02/1987         0.0  
15807  08/14/1998         0.0  
15808  04/10/1997         0.0  

[10915415 rows x 8 columns]

In [10]:
new_df['Race'] = new_df['Race'].replace([1],10)
new_df['Race'] = new_df['Race'].replace([2],1)
new_df['Race'] = new_df['Race'].replace([3],2)
new_df['Race'] = new_df['Race'].replace([4],3)
new_df['Race'] = new_df['Race'].replace([5],4)
new_df['Race'] = new_df['Race'].replace([6],10)
new_df['Race'] = new_df['Race'].replace([7],10)
new_df['Race'] = new_df['Race'].replace([8],10)
new_df['Race'] = new_df['Race'].replace([10],5)

In [11]:
new_df.Race.value_counts()

4    7648545
2    1396642
3    1239698
5     456966
1     173564
Name: Race, dtype: int64

In [12]:
final_df = pd.DataFrame(columns=columns)

for i in range(9):
    temp_df = new_df.loc[new_df['Race'] == i]
    temp_df = temp_df[:][:100000]
    df_list = [final_df, temp_df]
    final_df = pd.concat(df_list)

In [13]:
final_df.Race.value_counts()

5    100000
4    100000
3    100000
2    100000
1    100000
Name: Race, dtype: int64

In [14]:
final_df

CountyCode    VoterID  LastName  FirstName MiddleName Race         DOB  \
17            ALA  102092701   Estores      David     Suarez    1  08/04/1960   
86            ALA  102502801  Jarvinen      Vilma          J    1  02/12/1987   
142           ALA  111784844   Hossain      Begum          R    1  07/31/1956   
208           ALA  114347572      Tran        Cac        Van    1  10/28/1963   
248           ALA  114274710    Haider   Mohammad          L    1  12/16/1987   
...           ...        ...       ...        ...        ...  ...         ...   
672964        DAD  109872648  Benjamin       Mary          T    5  09/06/1932   
672968        DAD  109722566   Aguilar     Martha          G    5  02/11/1958   
672973        DAD  109863102   Claudio       Luis       Yoel    5  06/06/1981   
672988        DAD  109964609     Roges      Pedro          P    5  05/12/1946   
672996        DAD  110131886    Tuttle  Katherine          R    5  09/28/1983   

        Unnamed: 0  
17             0.0  
86             0.0  
142            0.0  
208            0.0  
248            0.0  
...            ...  
672964         0.0  
672968         0.0  
672973         0.0  
672988         0.0  
672996         0.0  

[500000 rows x 8 columns]

In [15]:
from collections import Counter
from imblearn.over_sampling import SMOTE
from matplotlib import pyplot
from numpy import where

In [16]:
final_df['name_last_name_first'] = final_df['LastName'] + ' ' + final_df['FirstName']

In [17]:
final_df

CountyCode    VoterID  LastName  FirstName MiddleName Race         DOB  \
17            ALA  102092701   Estores      David     Suarez    1  08/04/1960   
86            ALA  102502801  Jarvinen      Vilma          J    1  02/12/1987   
142           ALA  111784844   Hossain      Begum          R    1  07/31/1956   
208           ALA  114347572      Tran        Cac        Van    1  10/28/1963   
248           ALA  114274710    Haider   Mohammad          L    1  12/16/1987   
...           ...        ...       ...        ...        ...  ...         ...   
672964        DAD  109872648  Benjamin       Mary          T    5  09/06/1932   
672968        DAD  109722566   Aguilar     Martha          G    5  02/11/1958   
672973        DAD  109863102   Claudio       Luis       Yoel    5  06/06/1981   
672988        DAD  109964609     Roges      Pedro          P    5  05/12/1946   
672996        DAD  110131886    Tuttle  Katherine          R    5  09/28/1983   

        Unnamed: 0 name_last_name_first  
17             0.0        Estores David  
86             0.0       Jarvinen Vilma  
142            0.0        Hossain Begum  
208            0.0             Tran Cac  
248            0.0      Haider Mohammad  
...            ...                  ...  
672964         0.0        Benjamin Mary  
672968         0.0       Aguilar Martha  
672973         0.0         Claudio Luis  
672988         0.0          Roges Pedro  
672996         0.0     Tuttle Katherine  

[500000 rows x 9 columns]

In [18]:
NGRAMS = 2
vect = CountVectorizer(analyzer='char', max_df=0.3, min_df=3, ngram_range=(NGRAMS, NGRAMS), lowercase=False) 
name_vecs = vect.fit_transform(final_df.name_last_name_first)

In [19]:
vocab = vect.vocabulary_

In [20]:
words = []
for b in vocab:
    c = vocab[b]
    words.append((name_vecs[:, c].sum(), b))

words = sorted(words, reverse=True)
words_list = [w[1] for w in words]
num_words = len(words_list)
print("num_words = %d" % num_words)

num_words = 1850


In [21]:
def find_ngrams(text, n):
    a = zip(*[text[i:] for i in range(n)])
    wi = []
    for i in a:
        w = ''.join(i)
        try:
            idx = words_list.index(w)
        except:
            idx = 0
        wi.append(idx)
    return wi

In [22]:
X = np.array(final_df.name_last_name_first.apply(lambda c: find_ngrams(c, NGRAMS)))
X

array([list([403, 54, 64, 25, 17, 21, 8, 41, 88, 121, 94, 155]),
       list([85, 1, 443, 94, 6, 19, 9, 4, 174, 218, 29, 331, 53]),
       list([230, 51, 119, 89, 126, 6, 4, 79, 159, 245, 145, 325]), ...,
       list([265, 32, 125, 267, 170, 165, 37, 48, 238, 183, 24]),
       list([62, 440, 127, 21, 8, 108, 190, 152, 93, 52]),
       list([503, 282, 80, 418, 11, 30, 61, 166, 44, 43, 45, 2, 5, 6, 19])],
      dtype=object)

In [23]:
# check max/avg feature
X_len = []
for x in X:
    X_len.append(len(x))

max_feature_len = max(X_len)
avg_feature_len = int(np.mean(X_len))
print("Max feature len = %d, Avg. feature len = %d" % (max_feature_len, avg_feature_len))

Max feature len = 44, Avg. feature len = 12


In [24]:
y = np.array(final_df.Race.astype('category').cat.codes)
y

array([0, 0, 0, ..., 4, 4, 4], dtype=int8)

In [25]:
# Split train and test dataset
X_train,  X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

In [26]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((400000,), (400000,), (100000,), (100000,))

In [27]:
'''The dataset is actually too small for LSTM to be of any advantage
compared to simpler, much faster methods such as TF-IDF + LogReg.
Notes:

- RNNs are tricky. Choice of batch size is important,
choice of loss and optimizer is critical, etc.
Some configurations won't converge.

- LSTM loss decrease patterns during training can be quite different
from what you see with CNNs/MLPs/etc.
'''
import keras
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding, Dropout, Activation
from keras.layers import LSTM
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.models import load_model

max_features = num_words # 20000
feature_len = 20 # avg_feature_len # cut texts after this number of words (among top max_features most common words)
batch_size = 32

print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')

print('Pad sequences (samples x time)')
X_train = sequence.pad_sequences(X_train, maxlen=feature_len)
X_test = sequence.pad_sequences(X_test, maxlen=feature_len)
print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

num_classes = np.max(y_train) + 1
print(num_classes, 'classes')


400000 train sequences
100000 test sequences
Pad sequences (samples x time)
X_train shape: (400000, 20)
X_test shape: (100000, 20)
5 classes


In [28]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((400000, 20), (400000,), (100000, 20), (100000,))

In [29]:
counter = Counter(y_train)
print(counter)

Counter({0: 80000, 4: 80000, 1: 80000, 2: 80000, 3: 80000})


In [30]:
# transform the dataset
oversample = SMOTE()
newX, newy = oversample.fit_resample(X_train, y_train)
# summarize the new class distribution
counter = Counter(newy)
print(counter)

Counter({0: 80000, 4: 80000, 1: 80000, 2: 80000, 3: 80000})


In [31]:
newX.shape, newy.shape

((400000, 20), (400000,))

In [32]:
newX

array([[  0,   0,   0, ..., 214,  34, 146],
       [  0,   0,   0, ..., 121,  94,  24],
       [  0,   0,   0, ...,  75,   7,  14],
       ...,
       [  0,  92,  44, ..., 150, 171,  59],
       [  0,   0,   0, ..., 183,  76,  78],
       [  0,   0,   0, ..., 249, 187, 532]], dtype=int32)

In [33]:
X_train

array([[  0,   0,   0, ..., 214,  34, 146],
       [  0,   0,   0, ..., 121,  94,  24],
       [  0,   0,   0, ...,  75,   7,  14],
       ...,
       [  0,  92,  44, ..., 150, 171,  59],
       [  0,   0,   0, ..., 183,  76,  78],
       [  0,   0,   0, ..., 249, 187, 532]], dtype=int32)

In [34]:
print('Convert class vector to binary class matrix '
      '(for use with categorical_crossentropy)')
y_train_hot = keras.utils.to_categorical(newy, num_classes)
y_test_hot = keras.utils.to_categorical(y_test, num_classes)
print('y_train shape:', y_train_hot.shape)
print('y_test shape:', y_test_hot.shape)

Convert class vector to binary class matrix (for use with categorical_crossentropy)
y_train shape: (400000, 5)
y_test shape: (100000, 5)


In [35]:
print('Build model...')

model = Sequential()
model.add(Embedding(num_words, 32, input_length=feature_len))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(num_classes, activation='softmax'))

# try using different optimizers and different optimizer configs
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

print(model.summary())

Build model...
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 32)            59200     
_________________________________________________________________
lstm (LSTM)                  (None, 128)               82432     
_________________________________________________________________
dense (Dense)                (None, 5)                 645       
Total params: 142,277
Trainable params: 142,277
Non-trainable params: 0
_________________________________________________________________
None


In [36]:
SAMPLE = 1000000
EPOCHS = 10

In [37]:
print('Train...')
model.fit(newX, y_train_hot, batch_size=batch_size, epochs=EPOCHS,
          validation_split=0.1, verbose=2)
score, acc = model.evaluate(X_test, y_test_hot,
                            batch_size=batch_size, verbose=2)
print('Test score:', score)
print('Test accuracy:', acc)

Train...
Epoch 1/10
11250/11250 - 174s - loss: 1.1994 - accuracy: 0.5136 - val_loss: 1.1311 - val_accuracy: 0.5512
Epoch 2/10
11250/11250 - 170s - loss: 1.1298 - accuracy: 0.5481 - val_loss: 1.1019 - val_accuracy: 0.5647
Epoch 3/10
11250/11250 - 172s - loss: 1.1022 - accuracy: 0.5618 - val_loss: 1.0815 - val_accuracy: 0.5731
Epoch 4/10
11250/11250 - 1326s - loss: 1.0830 - accuracy: 0.5709 - val_loss: 1.0704 - val_accuracy: 0.5775
Epoch 5/10
11250/11250 - 184s - loss: 1.0688 - accuracy: 0.5769 - val_loss: 1.0636 - val_accuracy: 0.5823
Epoch 6/10
11250/11250 - 177s - loss: 1.0583 - accuracy: 0.5825 - val_loss: 1.0573 - val_accuracy: 0.5842
Epoch 7/10
11250/11250 - 197s - loss: 1.0502 - accuracy: 0.5857 - val_loss: 1.0470 - val_accuracy: 0.5913
Epoch 8/10
11250/11250 - 188s - loss: 1.0431 - accuracy: 0.5885 - val_loss: 1.0451 - val_accuracy: 0.5924
Epoch 9/10
11250/11250 - 173s - loss: 1.0383 - accuracy: 0.5914 - val_loss: 1.0400 - val_accuracy: 0.5935
Epoch 10/10
11250/11250 - 172s - los

## Confusion Matrix

In [40]:
y_pred = model.predict_classes(X_test, verbose=2)
p = model.predict_proba(X_test, verbose=2) # to predict probability
target_names = ['Asian Or Pacific Islander','Black, Not Hispanic','Hispanic','White, Not Hispanic','Other']
print(classification_report(np.argmax(y_test_hot, axis=1), y_pred, target_names=target_names))
print(confusion_matrix(np.argmax(y_test_hot, axis=1), y_pred))

3125/3125 - 9s
3125/3125 - 9s
                           precision    recall  f1-score   support

Asian Or Pacific Islander       0.73      0.64      0.68     20000
      Black, Not Hispanic       0.57      0.69      0.62     20000
                 Hispanic       0.66      0.80      0.72     20000
      White, Not Hispanic       0.49      0.75      0.59     20000
                    Other       0.37      0.07      0.12     20000

                 accuracy                           0.59    100000
                macro avg       0.57      0.59      0.55    100000
             weighted avg       0.57      0.59      0.55    100000

[[12732  1560  2293  2483   932]
 [  639 13853   450  4373   685]
 [  895   860 15957  1835   453]
 [  486  3183   929 14951   451]
 [ 2583  4937  4392  6638  1450]]


## Save model

In [36]:
model.save('./models/fl_voter_reg/lstm/fl_all_fullname_lstm_5_cat.h5')
words_df = pd.DataFrame(words_list, columns=['vocab'])
words_df.to_csv('./models/fl_voter_reg/lstm/fl_all_fullname_vocab_5_cat.csv', index=False, encoding='utf-8')